### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by ioridev** [pwwang/vscode-gptcommit#10]
Linux

DEBUG: gptcommit failed with error: Error: Command failed: /home/iori/.cargo/bin prepare-commit-msg --commit-msg-file /tmp/vscode-gptcommit-e7a1516a-7502-4df2-b379-b91f7c1712ad.txt --commit-source commit --git-diff-content /tmp/vscode-gptcommit-e7a1516a-7502-4df2-b379-b91f7c1712ad.diff
/bin/sh: 1: /home/iori/.cargo/bin: Permission denied
 | /bin/sh: 1: /home/iori/.cargo/bin: Permission denied

**Comment by pwwang** [comment]
The path is not correct. You probably need `/home/iori/.cargo/bin/gptcommit` for your gptcommit path.
