### ISSUE TITLE
Support older versions of VSCode

### ISSUE THREAD

**Issue by hewking** [pwwang/vscode-gptcommit#4]
Version: 1.71.0 (Universal)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:38.437Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No

上面是vscode 具体信息，可能是没有兼容这个版本

**Comment by pwwang** [comment]
We require 1.75+ for now. See if we can support older versions of VScode
