### ISSUE TITLE
Failed to set OpenAl API key: Error: Command failed:gptcommit config set openai.api key as 'gptcommit'

### ISSUE THREAD

**Issue by lxw15337674** [pwwang/vscode-gptcommit#6]
![image](https://user-images.githubusercontent.com/19898669/221078981-2ad77e19-71de-4d75-a8d1-14829ae72831.png)

this is my environment
![image](https://user-images.githubusercontent.com/19898669/221079062-39d3df42-37a5-4f0f-9e80-96ccb97b5b3a.png)

**Comment by pwwang** [comment]
Do you have the correct path point to `gptcommit`?

**Comment by lxw15337674** [comment]
oh,I ignored this, thanks。
