### ISSUE TITLE
Failed to generate commit message

### ISSUE THREAD

**Issue by lovebai** [pwwang/vscode-gptcommit#8]
Hello, I have encountered a problem where the plugin prompts 'failed to generate commit message'. I have checked my configuration several times but I don't know what is causing this issue.

![image](https://user-images.githubusercontent.com/42148495/227419448-53b25b98-2e61-45d7-91ea-a5d2332034bf.png)

![image](https://user-images.githubusercontent.com/42148495/227419027-4d992bad-f1e7-4849-bc97-a88845bee14a.png)
![image](https://user-images.githubusercontent.com/42148495/227419204-abdd4689-f618-49d0-943a-a5bb6444a4f8.png)

**Comment by pwwang** [comment]
Could you paste the output channel of GPTCommit?

**Comment by lovebai** [comment]
> Could you paste the output channel of GPTCommit?


```
COMMAND: C:\Users\degdev\.cargo\bin\gptcommit.exe prepare-commit-msg --commit-msg-file C:\Users\degdev\AppData\Local\Temp\vscode-gptcommit-bfc6d8b2-7b65-4fe5-99d0-e46a87419a6b.txt --commit-source commit --git-diff-content C:\Users\degdev\AppData\Local\Temp\vscode-gptcommit-bfc6d8b2-7b65-4fe5-99d0-e46a87419a6b.diff
STDOUT: 🤖 Skipping gptcommit since we're amending a commit. Change this behavior with `gptcommit config set allow_amend true`

STDERR: 
DEBUG: gptcommit failed to generate commit message, message file not generated
```
I tried to run this command `gptcommit config set allow_amend true`，But failed.

**Comment by pwwang** [comment]
What are the versions of your `vscode-gptcommit` and `gptcommit`?

**Comment by lovebai** [comment]
Thank you, I am using the latest version. I reinstalled `vscode-gptcommit` and `gptcommit`, and today I was able to use it normally.
