### ISSUE TITLE
GPT Commit error

### ISSUE THREAD

**Issue by ElProfessorFR** [pwwang/vscode-gptcommit#9]
I installed gptcommit via ``cargo install --locked gptcommit --version 0.3.0`` and when I try to generate the commit message I get this error in the output of GPTCommit (it repeats endlessly) I tried this ``gptcommit config set allow-amend true`` and that ``gptcommit config set allow-amend false``
```STDERR: 
DEBUG: allow_amend is false
COMMAND: C:\Users\MYNAME\.cargo\bin\gptcommit.exe config set allow_amend true
COMMAND: C:\Users\MYNAME\.cargo\bin\gptcommit.exe prepare-commit-msg --commit-msg-file C:\Users\aubin\AppData\Local\Temp\vscode-gptcommit-3a91c09d-e2c4-4e56-9784-aab3c01aedc7.txt --commit-source commit --git-diff-content C:\Users\MYNAME\AppData\Local\Temp\vscode-gptcommit-3a91c09d-e2c4-4e56-9784-aab3c01aedc7.diff
STDOUT: 🤖 Skipping gptcommit because commit is being amended
```

**Comment by drkostas** [comment]
I have the exact same problem with `vscode 1.76.2`, `gptcommit 0.3.0` and `vscode-gptcommit v0.2.1`.

**Comment by pwwang** [comment]
Are you able to run `gptcommit.exe config set allow_amend true` manually under the workspace and try again?

**Comment by ElProfessorFR** [comment]
I have to commit several times by hand and after do gptcommit install and modify the config to accept amend (Sorry for error, it's google trad)

**Comment by pwwang** [comment]
> I have to commit several times by hand and after do gptcommit install and modify the config to accept amend (Sorry for error, it's google trad)

Could you elaborate the steps? Let's see if we locate the culprit and fix this.

**Comment by pwwang** [comment]
It should be fixed at v0.2.2. Let me know if it still persists.

**Comment by drkostas** [comment]
For me, it works with the new version. Thanks!

**Comment by pwwang** [comment]
Closing. Feel free to reopen it if the issue persists.

**Comment by ElProfessorFR** [comment]
**Steps to solve the problem:**

1. Launch a commit where you write the message yourself.
2. Run gptcommit install in the local directory (it says not to do this in the readme but in my case it was necessary).
3. Restart vscode.
4. Edit the gptcommit config file, the workspace one (.git/gptcommit.toml), replacing `allow_amend = false` with `allow_amend = true`.
5. Restart VS Code, and now try to generate a message - it should work !
![image](https://user-images.githubusercontent.com/107270957/229272242-fe4c6456-3d00-4489-aae5-33ebc9ac9542.png)

**Comment by pwwang** [comment]
@ElProfessorFR Does the new version fix your issue?
